### ISSUE TITLE
kinda goroutine leak with pgx module in awaitDone

### ISSUE THREAD

**Issue by Olex1313** [avito-tech/go-transaction-manager#105]
Hello, I've been using trm for my personal projects with pgx backend and found out some edge case in [trm/v2/manager.go](https://github.com/avito-tech/go-transaction-manager/blob/main/trm/manager/manager.go).

Apparently, when a context with external cancel function is passed in `Manager.Do`, the pgx implementation of a transaction relies on context either have no Done channel or getting the cancel function [from manager](https://github.com/avito-tech/go-transaction-manager/blob/main/trm/manager/manager.go#L157). 

It is kinda fixed in #103 due to changes inside transaction implementations, but the latest release version v2.0.0-rc8 released before it and when I vendor the v2.0.0-rc8 it still contains leak, maybe I am doing something wrong?

**Comment by Khranovskiy** [comment]
Hello, there are two PRs that fix known memory-related problems: 
- [103](https://github.com/avito-tech/go-transaction-manager/pull/103) that merged in v1 branch with a tag v1.5.0  and
- [104](https://github.com/avito-tech/go-transaction-manager/pull/104) that for a main and tag v2.0.0-rc8. 

I have to take several days to check if release v2.0.0-rc8 contains the same fix as 103.

**Comment by Khranovskiy** [comment]
Good day, Alexey!
Sorry for the long reply, I checked and the latest version v2.0.0 contains a fix for the pgx module in awaitDone memory leak, you can use this version.
