### ISSUE TITLE
May be it's better to use generics?

### ISSUE THREAD

**Issue by F0rzend** [avito-tech/go-transaction-manager#111]
Your transaction contains method that returns "raw" tx (sql.Tx, sqlx.Tx, etc.) as interface{} (any):
https://github.com/avito-tech/go-transaction-manager/blob/main/trm/transaction.go#L44

It seems to me that the API will be more convenient if the transaction is made generalized (generic).

Something like:
```go
type Transaction[T any] interface {
	// Raw returns the real transaction sql.Tx, sqlx.Tx or another.
	Raw() T
	// Commit the trm.Transaction.
	// Commit should be used only inside Manager.
	Commit() error
	// Rollback the trm.Transaction.
	// Rollback should be used only inside Manager.
	Rollback() error
}
```

With this solution, you don't have to transform the interface to a specific transaction every time in your code.

What do you think about this? If you give approve, I could do it.

**Comment by maranqz** [comment]
Hi, sounds great, but will your generics solution be compatible with go1.17 and earlier?

**Comment by F0rzend** [comment]
> Hi, sounds great, but will your generics solution be compatible with go1.17 and earlier?

I don't think so... I understand you

**Comment by maranqz** [comment]
Okay, I close the issue but we can back for this after 1-2 years because it's good idea.
