### ISSUE TITLE
Clickhouse support?

### ISSUE THREAD

**Issue by hound672** [avito-tech/go-transaction-manager#113]
Does it make sense to add support for clickhouse?
Since it doesn't have transaction but has batch insert.
https://github.com/ClickHouse/clickhouse-go/blob/main/examples/clickhouse_api/batch.go

**Comment by maranqz** [comment]
I would ask Clickhouse's users.
I don't want to add maintenance complexity for unused code

**Comment by maranqz** [comment]
I close this issue.
If you found real example and users, just reopen or recreate new issue.
