### ISSUE TITLE
Can trManager manage a transaction if queries to the database are launched in parallel in different goroutines?

### ISSUE THREAD

**Issue by MaxBoych** [avito-tech/go-transaction-manager#114]
For example:
```
trManager.Do { 
    g := errGroup{}

    g.Go func1{ updateDB() }
    g.Go func2{ updateDB() }
    g.Go func3{ 
        updateDB()
        time.Sleep(5 seconds)
        return err // will the transaction work correctly?
    }

    return g.Wait()
}
```

**Comment by maranqz** [comment]
Hello,

Fast answer is yes but there is some restriction.

1. Creating nested transaction / savepoints could create problems.
2. If a database driver, not to be confused with the driver in the trm library, supports concurrency  processing.

Also, you can use `-race` option to check race condition problems.
Could you share more about your use case or more details code?

**Comment by maranqz** [comment]
I cannot run this code and I don't see problems.

However, you don't send `ctx` in `Update` and a transaction would not be sent inside repository.
