### ISSUE TITLE
Library close transaction 

### ISSUE THREAD

**Issue by maranqz** [avito-tech/go-transaction-manager#29]
[pgx](https://github.com/jackc/pgx) closes transaction on error.
Then the lib returns missing error of "commit unexpectedly resulted in rollback".

**Comment by hound672** [comment]
I checked this behavior in https://github.com/avito-tech/go-transaction-manager/pull/76
If I return `trm.ErrSkip` in transaction section transaction will be commited.
Is this correct?

**Comment by maranqz** [comment]
ErrSkip  doesn't connect with ErrTxCommitRollback.
ErrSkip ables to commit on an application error not a database.

I think, I can close this issue, because the pgx [docs](https://github.com/jackc/pgx/blob/a7375cc503268d34a0312d22c9c17f6e943f654b/tx.go#L86C65-L86C65) said: `PostgreSQL accepts COMMIT on aborted transactions, but px is treated as ROLLBACK.`
