### ISSUE TITLE
Add pgx support

### ISSUE THREAD

**Issue by ansakharov** [avito-tech/go-transaction-manager#30]
Currently library supports postgres through sqlx, but not pgx.

**Comment by maranqz** [comment]
While you are waiting the adapter for pgx, you can use the library with [pgx through database/sql interface](https://github.com/jackc/pgx/wiki/Getting-started-with-pgx-through-database-sql).

**Comment by maranqz** [comment]
https://github.com/avito-tech/go-transaction-manager/pull/76
