### ISSUE TITLE
Separate drivers

### ISSUE THREAD

**Issue by hound672** [avito-tech/go-transaction-manager#75]
Hello.
For now this github repository contains main functionality and drivers/plugins for different databases.
Do you think about separated repositories?
One with main functionality, and another for drivers/plugins (each for plugin: 1 for pgx, 1 for redis etc).

**Comment by maranqz** [comment]
Hello,
I don't think about it, but it is a good idea.
If you create a pull request with these changes, I'll be happy to review it.

**Comment by hound672** [comment]
Ok, but now i'd like to implement pgx support, if you don't mind.
I really like you approach. I made an approach that similar to yours (also use ctx to share transaction).

**Comment by hound672** [comment]
I think that the main repository should contain only `trm` package and hence only basic deps.
And for each adapters should be its own repository. But where? This space?
What do you think?

**Comment by maranqz** [comment]
I think we can add go.mod to each adapter and store it all in the one repository.
Creating repos for each adapter adds extra work. 

Also I would check what will happen with the old code.
Should version be bumped up to v2, or is it enough for the lib users to update go.mod?

**Comment by hound672** [comment]
> I think we can add go.mod to each adapter and store it all in the one repository.

Hm... `go get https://github.com/avito-tech/go-transaction-manager/pgx` for example to install pgx adapter? 

> version be bumped up to v2

I think yes, since it breaks current api.

**Comment by hound672** [comment]
> I think we can add go.mod to each adapter and store it all in the one repository.

Hm... `go get https://github.com/avito-tech/go-transaction-manager/pgx` for example to install pgx adapter? 

> version be bumped up to v2

I think yes, since it breaks current api.

**Comment by maranqz** [comment]
> Hm... go get https://github.com/avito-tech/go-transaction-manager/pgx for example to install pgx adapter?

Yeap)

> > version be bumped up to v2
> 
> I think yes, since it breaks current api.

`MAJOR version when you make incompatible API changes` https://semver.org/
I'm not sure that we change API at all. I hope `go mod tidy` would be enough to update)

**Comment by maranqz** [comment]
@hound672 you can check 
```
go get github.com/avito-tech/go-transaction-manager/trm/v2@v2.0.0-rc6
go get github.com/avito-tech/go-transaction-manager/drivers/pgxv4/v2@v2.0.0-rc6 
```

**Comment by hound672** [comment]
Looks good!
Thanks!

**Comment by maranqz** [comment]
#96 Merged
