### ISSUE TITLE
Support for dgraph-io/badger

### ISSUE THREAD

**Issue by Olex1313** [avito-tech/go-transaction-manager#91]
Hello, I've wanted to add support for https://github.com/dgraph-io/badger, but most recent badger/v4 uses go 1.19, and trm is 1.13 due to backward compatibility. So I have a few questions

1. will go-transaction-manager bump its go version someday?
2. How can I contribute with badger support without bumping go version? I am aming for supporting badger/v4, maybe with separate it with build-tags?
3. Could I fork go-transaction-manager for my personal usage and bump go there?

**Comment by maranqz** [comment]
Hello, 

1. I am not planning to bump the version.
2. You can see the gorm [example](https://github.com/avito-tech/go-transaction-manager/blob/main/gorm/transaction.go), which supports only going 1.16  and up by build tags.
3. I cannot forbid you to fork. It is your right :) However, I suggest you use the gorm approach to add badger in go-transaction-manager. 

I want to separate the interface and implementation in different go.mod packages. When it would be done, I don't know.
There is an issue with that https://github.com/avito-tech/go-transaction-manager/issues/75

**Comment by maranqz** [comment]
Yes, you can continue my pr or review it.
https://github.com/avito-tech/go-transaction-manager/pull/92

**Comment by maranqz** [comment]
If you have a desire to contribute, reopen the issues and feel free to create a PR.
